sudo: required
language: cpp
env:
  global:
  - APT_DEPENDENCIES="doxygen libltdl-dev libboost-all-dev liblog4cxx10-dev libyaml-cpp-dev"
  - HOMEBREW_DEPENDENCIES="doxygen log4cxx yaml-cpp"
  - GIT_DEPENDENCIES="roboptim/roboptim-core"
  - DEBSIGN_KEYID=5AE5CD75
  - PPA_URI="roboptim/ppa"
  - GH_USERNAME=thomas-moulard
  - GH_REPO=roboptim/roboptim-core-config
  - LCOV_IGNORE_RULES="*tests*"
  - secure: fURGUkCIPnZZ4G+Gaf9wMPH2P8sXiDA0kA1S6qVdCbenIyilRNnLmPiqHoqwtVEl4pqpdmRoFnMbJMGIuh+61gdo23+MZ1TBeNUp86nkH4v+qVRw5n1Nm2cKJZiqiuRHcTF3jVCVgx7eUvDkPAjJ9ff4vxB8sQhOQkQeGilJyak=
  - secure: TBMOOJtRFuQK9NWIlKuBg+/LiuTa8Hz+8PsnZB/vGlc4FpoRJkz7DmnQS/sCDxunhaXZX6rac7THzCn6lrp5wksXNRRqUwRiv+JixyE1WbAnn22JBEouhs4o4fjRtwPvvkH0+EpAxuSebltCESrdxfjjkeLine4CZvV0e6HPquw=
  - secure: ALE6izEg9T+fqCBUvvhKEgOgCnR+43DSOFT/DDBIj2hCXlf9R9dQ8upaG/6JXl08i5hwVRvQMK9+zJfU25cTTM/xpC8O/5G8t7pG9Y+/QeVOMbOCQnHMDe7dB8azO8CHnC91pP00ychf8KSL2Exz+o1k1fha/9BaZZDo5zCrKKU=
  - secure: "YOeurB3pqF+B5iJHQBq4HtBoTW6PcDaNFuvDqVC64huArDZ9jjZt7EqDVEHJwuwMxrLW94lgdR9DAOwAM+X5EaMlekJ2h56not7U+553/NZYLC4MgimGOAn127kaO7CacZmdYNjQNq+G8pXJX/N+VSaqLy+WhM6Kuxts0CDC1UM="
notifications:
  email: roboptim@googlegroups.com
branches:
  only:
    - master
    - dev
    - debian
    - travis

before_install:
  - pip install --user codecov
  - ./.travis/dependencies/eigen-3.2
  - ./.travis/run before_install
script:
  - export LD_LIBRARY_PATH="/tmp/_ci/install/lib/roboptim-core/":$LD_LIBRARY_PATH
  - ./.travis/run build
after_success:
  - ./.travis/run after_success
  - codecov --gcov-root=/tmp/_ci/build
after_failure: ./.travis/run after_failure

matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: clang
    - os: osx
      compiler: clang
    - os: osx
      compiler: gcc
